### ISSUE TITLE
Support plain badges

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/formidable-oss-badges#7]
Add an option for plain badges with central svg logos instead of text. Plain badges should have a single outline with no number bubble and no lower text area. This will allow us to make hex badges for projects that have logos like Victory and Urql

**Comment by VirtualDOMinic** [comment]
@boygirl we're currently going ahead with no number bubble, but I just wanted to double check this is the case, as I noticed that the Victory logo on the [spectacle docs](https://formidable.com/open-source/spectacle/) has a number at the top (`01`)
