### ISSUE TITLE
Font flash in static site / SSR 

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/formidable-oss-badges#8]
I noticed this when getting ready to deploy spectacle docs to staging:
![font-flash](https://user-images.githubusercontent.com/3719995/56755057-741c6b00-6743-11e9-8ca4-21bc02b05c30.gif)

Steps to reproduce from `spectacle-docs`
1) `yarn stage-and-serve`
2) navigate to http://localhost:3000/open-source/spectacle/

**Comment by VirtualDOMinic** [comment]
LGTM!

Thanks for the spot and the fix! Can confirm I could recreate it too
